project:
  type: website
  output-dir: docs

website:
  title: "AI_theory"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css


gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0




# test
author:
    name: 이정재

nav:
    Contents:
     - '/blog/'
     - { ML_theory: '/blog/ML_theory/' }
     - { DL_theory: '/blog/DL_theory/' }
    About:
     - '/about/'

ML_theory_page: '/blog/ML_theory/'
DL_theory_page: '/blog/DL_theory/'




